import { Airport } from '@/types/airport';

export const ALL_AIRPORTS: Airport[] = [
  {
    id: 'apt-mm2-lagos',
    code: 'MM2',
    name: 'Murtala Muhammed Airport Terminal 2',
    shortName: 'MM2 Lagos',
    city: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    currency: 'NGN',
    currencySymbol: '₦',
    timezone: 'Africa/Lagos',
    status: 'ACTIVE',
    launchYear: 2025,
    heroImageUrl: 'https://images.unsplash.com/photo-1542296332-2e4473faf563?q=80&w=1200&auto=format&fit=crop',
    description: 'Nigeria’s flagship modern domestic terminal. Serving domestic passenger flights across Nigeria with top-tier security and streamlined departures.',
    terminals: [
      { id: 'mm2-main', name: 'Main Domestic Terminal', code: 'MM2-D1', description: 'Primary terminal for domestic departures & arrivals.' },
    ],
    services: [
      {
        serviceId: 'porter',
        name: 'Verified Airport Porter',
        priceNGN: 5000,
        unit: 'per booking (up to 3 bags)',
        available: true,
        tagline: 'Uniformed, background-checked porters to handle your baggage seamlessly.',
        description: 'Meet your dedicated uniformed porter right at curbside departure or baggage claim. Hands-free airport movement.',
      },
      {
        serviceId: 'cab',
        name: 'Verified Executive Airport Cab',
        priceNGN: 15000,
        unit: 'average fixed fare',
        available: true,
        tagline: 'Chauffeur-driven, air-conditioned executive sedans & SUVs with guaranteed arrival.',
        description: 'Skip driver haggling. Verified drivers waiting at arrival curbside with flight tracking.',
      },
      {
        serviceId: 'lounge',
        name: 'Executive VIP Lounge Access',
        priceNGN: 20000,
        unit: 'per guest / 3 hours',
        available: true,
        tagline: 'High-speed Wi-Fi, premium dining, quiet workstations & complimentary drinks.',
        description: 'Escape terminal noise in our curated partner lounges before your departure flight.',
      },
      {
        serviceId: 'fasttrack',
        name: 'Fast Track Security & Check-in',
        priceNGN: 0,
        unit: 'coming soon',
        available: false,
        comingSoon: true,
        tagline: 'Express lane access through security screening and priority check-in counters.',
        description: 'Bypass long airport queues with dedicated fast-lane clearance.',
      },
    ],
    operatingHours: '24 Hours / 7 Days a week',
    contact: {
      phone: '+234 1 800 5674',
      email: 'mm2@loshub.com',
      supportHours: '05:00 AM - 11:00 PM WAT',
    },
    coordinates: {
      latitude: 6.5774,
      longitude: 3.3211,
    },
  },
  {
    id: 'apt-mmia-lagos',
    code: 'MMIA',
    name: 'Murtala Muhammed International Airport',
    shortName: 'MMIA Lagos (International)',
    city: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    currency: 'NGN',
    currencySymbol: '₦',
    timezone: 'Africa/Lagos',
    status: 'EXPANDING_SOON',
    launchYear: 2026,
    heroImageUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=1200&auto=format&fit=crop',
    description: 'Lagos main international terminal connecting West Africa to global hubs. Service launch in progress.',
    terminals: [
      { id: 'mmia-t1', name: 'International Terminal 1', code: 'MMIA-T1', description: 'Legacy international departure terminal.' },
      { id: 'mmia-t2', name: 'New Terminal 2', code: 'MMIA-T2', description: 'State-of-the-art international departure terminal.' },
    ],
    services: [
      {
        serviceId: 'porter',
        name: 'Verified Airport Porter',
        priceNGN: 7500,
        unit: 'per booking',
        available: false,
        comingSoon: true,
        description: 'Uniformed porter service for international arrivals and departures.',
      },
      {
        serviceId: 'cab',
        name: 'Verified Executive Airport Cab',
        priceNGN: 20000,
        unit: 'fixed rate to VI / Ikoyi',
        available: false,
        comingSoon: true,
        description: 'Verified airport pickup with driver flight monitoring.',
      },
      {
        serviceId: 'lounge',
        name: 'VIP International Lounge Access',
        priceNGN: 35000,
        unit: 'per guest',
        available: false,
        comingSoon: true,
        description: 'Premium international lounge access with shower facilities.',
      },
    ],
    operatingHours: '24 Hours',
    contact: {
      phone: '+234 1 800 5674',
      email: 'mmia@loshub.com',
      supportHours: '24/7 Operations',
    },
    coordinates: {
      latitude: 6.5774,
      longitude: 3.3211,
    },
  },
  {
    id: 'apt-abuja',
    code: 'ABV',
    name: 'Nnamdi Azikiwe International Airport',
    shortName: 'Abuja Airport (ABV)',
    city: 'Abuja',
    country: 'Nigeria',
    countryCode: 'NG',
    currency: 'NGN',
    currencySymbol: '₦',
    timezone: 'Africa/Lagos',
    status: 'EXPANDING_SOON',
    launchYear: 2026,
    heroImageUrl: 'https://images.unsplash.com/photo-1570710891163-6d3b5c47248b?q=80&w=1200&auto=format&fit=crop',
    description: 'Federal Capital Territory premier airport gateway serving government, diplomatic, and executive travelers.',
    terminals: [
      { id: 'abv-dom', name: 'Abuja Domestic Terminal', code: 'ABV-D', description: 'Domestic flights connecting Abuja to Lagos and key cities.' },
    ],
    services: [
      {
        serviceId: 'porter',
        name: 'Verified Airport Porter',
        priceNGN: 5000,
        unit: 'per booking',
        available: false,
        comingSoon: true,
        description: 'Executive porter service at Abuja airport.',
      },
      {
        serviceId: 'cab',
        name: 'Executive Airport Cab',
        priceNGN: 18000,
        unit: 'average fare to Central Business District',
        available: false,
        comingSoon: true,
        description: 'Direct transfer to Maitama, Asokoro, and CBD.',
      },
      {
        serviceId: 'lounge',
        name: 'Executive VIP Lounge',
        priceNGN: 25000,
        unit: 'per guest',
        available: false,
        comingSoon: true,
        description: 'Executive diplomatic lounge access.',
      },
    ],
    operatingHours: '24 Hours',
    contact: {
      phone: '+234 1 800 5674',
      email: 'abuja@loshub.com',
      supportHours: '06:00 AM - 10:00 PM',
    },
    coordinates: {
      latitude: 9.0068,
      longitude: 7.2632,
    },
  },
  {
    id: 'apt-phc',
    code: 'PHC',
    name: 'Port Harcourt International Airport',
    shortName: 'Port Harcourt (PHC)',
    city: 'Port Harcourt',
    country: 'Nigeria',
    countryCode: 'NG',
    currency: 'NGN',
    currencySymbol: '₦',
    timezone: 'Africa/Lagos',
    status: 'EXPANDING_SOON',
    launchYear: 2026,
    heroImageUrl: 'https://images.unsplash.com/photo-1508873696983-2df515122519?q=80&w=1200&auto=format&fit=crop',
    description: 'Oil & Gas hub airport serving Rivers State and Niger Delta corporate business travelers.',
    terminals: [
      { id: 'phc-main', name: 'Main Passenger Terminal', code: 'PHC-T1', description: 'Domestic and regional departures.' },
    ],
    services: [
      {
        serviceId: 'porter',
        name: 'Verified Airport Porter',
        priceNGN: 5000,
        unit: 'per booking',
        available: false,
        comingSoon: true,
        description: 'Baggage handling service.',
      },
      {
        serviceId: 'cab',
        name: 'Verified Airport Cab',
        priceNGN: 20000,
        unit: 'average fare to GRA',
        available: false,
        comingSoon: true,
        description: 'Chauffeur transport to Port Harcourt city.',
      },
    ],
    operatingHours: '06:00 AM - 09:00 PM',
    contact: {
      phone: '+234 1 800 5674',
      email: 'phc@loshub.com',
      supportHours: '06:00 AM - 09:00 PM',
    },
    coordinates: {
      latitude: 5.0154,
      longitude: 6.9496,
    },
  },
];

export const DEFAULT_AIRPORT_CODE = 'MM2';
